- mamba/formatters.py
Sometimes, when there is a lot of spec files is very dificult to identify the failing spec without printing the filename.
What do you think?
> Show the spec filename on each error

- README.md
Unfortunately, Markdown doesn't seem to support links inside code blocks, so I had to use comments to add references.
PS: nice work with `mamba`, I'm enjoying it so far!
> Document coverage measurement support

- .coveragerc
- .travis.yml
- circle.yml
Using a `.coveragerc` is cleaner, as you can specify which files to measure coverage on, instead of running it in the whole project and then filter in `coverage report`.
This includes a very simple `.coveragerc` template, but I guess not all files from `./mamba` should be included. However, in my experience, spec files should not be included in coverage measurement, as they are obviously going to have 100% coverage (the test code does run, or else you have a bigger problem), which would probably skew the coverage results upwards. Further, spec files are typically not part of the code you're acutally interested in covering. For these reasons, I didn't include it in the `.coveragerc`.
This `.coveragerc` file also instructs `coverage` to measure branch coverage, which is disabled by default.
> Use .coveragerc file

- mamba/example.py
- mamba/formatters.py
- mamba/loader.py
- mamba/nodetransformers.py
This is a simple spec:
```python
with describe("e 1."):
with context("l 1.1."):
with it("k 1.1.1."):
pass
with it("g 1.1.2."):
pass
with it("d 1.1.3."):
pass
with context("n 1.2."):
with it("i 1.2.1."):
pass
with it("a 1.2.2."):
pass
with context("c 1.3."):
with it("q 1.3.1."):
pass
with describe("m 2."):
with context("j 2.1."):
with it("o 2.1.1."):
pass
with it("b 2.1.2."):
pass
with context("p 2.2."):
with it("h 2.2.1."):
pass
with it("f 2.2.2."):
pass
```
Current mamba runs it in alphanumeric order:
```
e 1.
c 1.3.
✓ it q 1.3.1.
l 1.1.
✓ it d 1.1.3.
✓ it g 1.1.2.
✓ it k 1.1.1.
n 1.2.
✓ it a 1.2.2.
✓ it i 1.2.1.
m 2.
j 2.1.
✓ it b 2.1.2.
✓ it o 2.1.1.
p 2.2.
✓ it f 2.2.2.
✓ it h 2.2.1.
10 examples ran in 0.0124 seconds
```
After the patch it is ran in natural order (from top to bottom): …
> Run example groups and examples in natural order (not alphanumeric)

- mamba/example_collector.py
Hi
When using mamba for testing code that is not a pagkage yet (or maybe never will, like when you are doing a kata) I usually end up with this probem:
```
$ mamba
Traceback (most recent call last):
File "/home/alejandro/Code/value-objects/env/bin/mamba", line 9, in <module>
load_entry_point('mamba==0.8.5', 'console_scripts', 'mamba')()
File "/home/alejandro/Code/value-objects/mamba/mamba/cli.py", line 19, in main
runner.run()
File "/home/alejandro/Code/value-objects/mamba/mamba/runners.py", line 27, in run
for module in self.example_collector.modules():
File "/home/alejandro/Code/value-objects/mamba/mamba/example_collector.py", line 20, in modules
with self._load_module_from(path) as module:
File "/nix/store/ss1aq46xwhnqikq5bjs02sb9xrim2bb3-python-2.7.10/lib/python2.7/contextlib.py", …
```
> Allow importing of local non-installed modules and packages

- mamba/settings.py
There is no additional logic which needs to be executed on property access or change. And all members of Settings are being accessed after creation, so they can be considered public for all purposes. Hence we don't need the property mechanism, and it can be introduced without breaking anything whenever it's needed.
> Settings: no need to use properties for the moment, so remove them

- .gitignore
- mamba/example.py
- spec/errors_in_hooks_spec.py
There was an if statement that checked for errors and only ran code in after.each if there were none. Removed this if check.
> Fixes issue #96 - after.each only executes if examples pass. 

- docs/formatters.rst
Fix documentation line on section Formatters.
Corrected typo on command name `maba` → `mamba`
> Fix command name `maba` → `mamba` on docs

- mamba/example.py
- mamba/formatters.py
- mamba/loader.py
- mamba/nodetransformers.py
I added a little decorator that can be used by the node transformer to add arbitrary attributes to the generated functions and classes.
Using this decorator I moved all the relevant information about the generated examples and groups into attributes of the class/function instead of encoding it in the name.
The introduced attributes are:
* `_example`: True when the method is an example
* `_example_group`: True when the class is an example group
* `_pending`: True when the example or group is pending
* `_tags`: List of tags
* `_example_name`: Description of the example/group, which can now directly be used by the formatter without first having to remove underbars etc.
> Example Collector: Use class/function attributes instead of encoding information in name

- mamba/__init__.py
- mamba/example_group.py
- mamba/loader.py
- mamba/nodetransformers.py
- spec/example_collector_spec.py
- spec/fixtures/with_included_context.py
- spec/fixtures/with_shared_context.py
- spec/object_mother.py
- spec/shared_example_group_spec.py
I added two new example group contexts `shared_context` and `included_context`.
Any `shared_context` will not be executed on its own but will be inserted in any place where you use the context `included_context` **with the same description** . 
Example:
```python
with shared_context('Request tests'):
with context('When the request succeeds'):
with before.each:
with it('returns HTTP Status Code 200'):
...
with context('When the request fails'):
...
with describe('GET /api/important_data'):
with before.all:
with included_context('Request tests'):
pass
with describe('POST /api/dangerous'):
with before.all:
with included_context('Request tests'):
with it('additional security test'):
pass
```
As demonstrated by the (maybe too simple?) tests, any examples defined inside the `included_context` …
> Shared contexts

- mamba/example_group.py
- mamba/loader.py
- spec/refactoring_goodies_spec.py
I improved the binding of execution contexts for helper methods.
When a helper methods is defined in an example group it would be **permanently** bound to that particular execution context at that time. When creating a fresh copy of the execution context for nested examples/example groups, that reference would not be updated**, which would result in strange inconsistencies like:
```python
with context('Context'):
def helper(self):
return self.value + 1
with it('example'):
self.value = 3
expect(self.helper()).to(equal(4))  # Raises NameError instead
```
1. Bind helper methods after (and not before) copying the context
2. Always Inherit the helper method map from the parent context before adding own helper methods to it, so all methods can be bound the right current execution context.
** …
> Improve execution context binding of helper methods

- MANIFEST.in
Since mamba uses pipenv, this should not be in the MANIFEST.in file
> Remove requirements.txt file from MANIFEST.in

- mamba/example_group.py
- spec/hooks_spec.py
> Fix hooks: double *alls and reversed teardown ordering.

- mamba/__init__.py
Some python linters marks `with after.each` or `before.each` blocks as warning because method has not `each` property. They are defined as functions at `__init__.py`, so I added a contextmanganer decorator for `before, before_all, after, after_all` to avoid this warnings.
> Avoid linter warning: before and after has not method each

- README.md
An example for using `spec_helper.py` as file settings
> Update README, use spec_helper.py for default settings

- .travis.yml
- mamba/nodetransformers.py
**What this PR does / why we need it**:
This PR makes mamba to work on Python 3.8.
It also enables those platforms on CI
**Which issue(s) this PR fixes**:
Refs #144 
**Special notes for your reviewer**:
> Enable Python3.8 support

- mamba/application_factory.py
- mamba/example.py
- mamba/formatters.py
- mamba/loader.py
I added a JUnit xml formatter, which generates an XML file that can be read by CircleCI.
For now the content of the XML is output to stdout and thus can be redirected into a file with `>`...
Should I add something like an `--output`?
> Add JUnit XML Formatter

- mamba/formatters.py
**What this PR does / why we need it**:
This PR fixes the assertion error location specified in #115
This is only valid in case of expects, but I'm not sure how it will
behave with other expectation libraries.
**Which issue(s) this PR fixes**:
Refs #115
**Special notes for your reviewer**:
> fix(formatters): Specify exact line which raises the assertion

- CHANGES.md
- mamba/__init__.py
- mamba/formatters.py
**What this PR does / why we need it**:
The 'time' field in the JUnit formatter was output as `0:00:00.693097'  instead of just plain seconds, like `0.693097`. JUnit consumers just taking it as a string worker, but if they tried to parse it as a float, it failed. 
**Special notes for your reviewer**:
> fix: change junit 'time' field format, as it breaks some importers when parsing it

- Pipfile
- setup.py
- spec/mock_patch_example_spec.py
**What this PR does / why we need it**:
Remove references to mock backport since mamba only supports Python 3
**Special notes for your reviewer**:
I haven't touched `Pipfile.lock` because I am not familiar with the pipenv workflow.
> Remove references to mock backport since mamba only supports Python 3
